apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-java-mysql-k8s-deployment
spec:
  selector:
    matchLabels:
      app: springboot-java-mysql-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-java-mysql-k8s
    spec:
      containers:
        - name: springboot-java-mysql-k8s
          image: springboot-java-mysql-docker-image:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 100m